<?php

namespace FUT\ARManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CardsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardsRepository extends EntityRepository
{

	public function findAllByPlayersAttributes($orderBy, $order, $status)
	{
		$qb = $this->createQueryBuilder('c');
		$qb->join('c.player','p')
		   ->orderBy('p.'.$orderBy, $order)
		   ->where('c.status = :status')
		   		->setParameter('status',$status);

		return $qb->getQuery()->getResult();
	}



	public function findPlayersToRebuy()
	{
		/*$qb = $this->createQuery('SELECT DISTINCT c.player FROM FUT\ARManagerBundle\Entity\Cards c INNER JOIN FUT\ARManagerBundle\Entity\Players p ON c.player_id = p.id WHERE p.lastName NOT IN(SELECT DISTINCT p.lastName FROM FUT\ARManagerBundle\Cards c INNER JOIN FUT\ARManagerBundle\Entity\Players p ON c.player_id = p.id WHERE c.status="Listé" GROUP BY c.player_id)');
		return $qb->getResult();*/
	}
}
